// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/hr.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Employee struct {
	EmployeeId           int32    `protobuf:"varint,1,opt,name=employee_id,json=employeeId,proto3" json:"employee_id,omitempty"`
	EmployeeCode         string   `protobuf:"bytes,2,opt,name=employee_code,json=employeeCode,proto3" json:"employee_code,omitempty"`
	FullName             string   `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	JobTitle             string   `protobuf:"bytes,4,opt,name=job_title,json=jobTitle,proto3" json:"job_title,omitempty"`
	LegalId              int32    `protobuf:"varint,5,opt,name=legal_id,json=legalId,proto3" json:"legal_id,omitempty"`
	LegalName            string   `protobuf:"bytes,6,opt,name=legal_name,json=legalName,proto3" json:"legal_name,omitempty"`
	DepartmentId         int32    `protobuf:"varint,7,opt,name=department_id,json=departmentId,proto3" json:"department_id,omitempty"`
	DepartmentName       string   `protobuf:"bytes,8,opt,name=department_name,json=departmentName,proto3" json:"department_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Employee) Reset()         { *m = Employee{} }
func (m *Employee) String() string { return proto.CompactTextString(m) }
func (*Employee) ProtoMessage()    {}
func (*Employee) Descriptor() ([]byte, []int) {
	return fileDescriptor_de41ad8d5430b170, []int{0}
}

func (m *Employee) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Employee.Unmarshal(m, b)
}
func (m *Employee) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Employee.Marshal(b, m, deterministic)
}
func (m *Employee) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Employee.Merge(m, src)
}
func (m *Employee) XXX_Size() int {
	return xxx_messageInfo_Employee.Size(m)
}
func (m *Employee) XXX_DiscardUnknown() {
	xxx_messageInfo_Employee.DiscardUnknown(m)
}

var xxx_messageInfo_Employee proto.InternalMessageInfo

func (m *Employee) GetEmployeeId() int32 {
	if m != nil {
		return m.EmployeeId
	}
	return 0
}

func (m *Employee) GetEmployeeCode() string {
	if m != nil {
		return m.EmployeeCode
	}
	return ""
}

func (m *Employee) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *Employee) GetJobTitle() string {
	if m != nil {
		return m.JobTitle
	}
	return ""
}

func (m *Employee) GetLegalId() int32 {
	if m != nil {
		return m.LegalId
	}
	return 0
}

func (m *Employee) GetLegalName() string {
	if m != nil {
		return m.LegalName
	}
	return ""
}

func (m *Employee) GetDepartmentId() int32 {
	if m != nil {
		return m.DepartmentId
	}
	return 0
}

func (m *Employee) GetDepartmentName() string {
	if m != nil {
		return m.DepartmentName
	}
	return ""
}

type EmployeeReq struct {
	EmployeeCode         string   `protobuf:"bytes,1,opt,name=employee_code,json=employeeCode,proto3" json:"employee_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmployeeReq) Reset()         { *m = EmployeeReq{} }
func (m *EmployeeReq) String() string { return proto.CompactTextString(m) }
func (*EmployeeReq) ProtoMessage()    {}
func (*EmployeeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_de41ad8d5430b170, []int{1}
}

func (m *EmployeeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeReq.Unmarshal(m, b)
}
func (m *EmployeeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeReq.Marshal(b, m, deterministic)
}
func (m *EmployeeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeReq.Merge(m, src)
}
func (m *EmployeeReq) XXX_Size() int {
	return xxx_messageInfo_EmployeeReq.Size(m)
}
func (m *EmployeeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeReq.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeReq proto.InternalMessageInfo

func (m *EmployeeReq) GetEmployeeCode() string {
	if m != nil {
		return m.EmployeeCode
	}
	return ""
}

type EmployeeRes struct {
	Employee             *Employee `protobuf:"bytes,1,opt,name=employee,proto3" json:"employee,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *EmployeeRes) Reset()         { *m = EmployeeRes{} }
func (m *EmployeeRes) String() string { return proto.CompactTextString(m) }
func (*EmployeeRes) ProtoMessage()    {}
func (*EmployeeRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_de41ad8d5430b170, []int{2}
}

func (m *EmployeeRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmployeeRes.Unmarshal(m, b)
}
func (m *EmployeeRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmployeeRes.Marshal(b, m, deterministic)
}
func (m *EmployeeRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmployeeRes.Merge(m, src)
}
func (m *EmployeeRes) XXX_Size() int {
	return xxx_messageInfo_EmployeeRes.Size(m)
}
func (m *EmployeeRes) XXX_DiscardUnknown() {
	xxx_messageInfo_EmployeeRes.DiscardUnknown(m)
}

var xxx_messageInfo_EmployeeRes proto.InternalMessageInfo

func (m *EmployeeRes) GetEmployee() *Employee {
	if m != nil {
		return m.Employee
	}
	return nil
}

func init() {
	proto.RegisterType((*Employee)(nil), "proto.Employee")
	proto.RegisterType((*EmployeeReq)(nil), "proto.EmployeeReq")
	proto.RegisterType((*EmployeeRes)(nil), "proto.EmployeeRes")
}

func init() { proto.RegisterFile("proto/hr.proto", fileDescriptor_de41ad8d5430b170) }

var fileDescriptor_de41ad8d5430b170 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xcd, 0x4e, 0x83, 0x40,
	0x10, 0xc7, 0x43, 0x95, 0x16, 0x86, 0xb6, 0x24, 0x73, 0x42, 0x8d, 0xb1, 0xa1, 0x07, 0x9b, 0x98,
	0xd4, 0x04, 0xe3, 0xc5, 0xab, 0x31, 0x91, 0x8b, 0x07, 0xf4, 0x4e, 0xa0, 0x3b, 0x56, 0x9a, 0xa5,
	0x4b, 0xe9, 0x6a, 0xe2, 0x6b, 0xf8, 0xc4, 0x86, 0xc1, 0xa5, 0x8d, 0x9c, 0xd8, 0xfd, 0xfd, 0x3f,
	0x36, 0x33, 0xc0, 0xb4, 0xaa, 0x95, 0x56, 0xb7, 0x1f, 0xf5, 0x92, 0x0f, 0x68, 0xf3, 0x27, 0xfc,
	0x19, 0x80, 0xf3, 0x54, 0x56, 0x52, 0x7d, 0x13, 0xe1, 0x15, 0x78, 0xf4, 0x77, 0x4e, 0x0b, 0x11,
	0x58, 0x33, 0x6b, 0x61, 0x27, 0x60, 0x50, 0x2c, 0x70, 0x0e, 0x93, 0xce, 0xb0, 0x52, 0x82, 0x82,
	0xc1, 0xcc, 0x5a, 0xb8, 0xc9, 0xd8, 0xc0, 0x47, 0x25, 0x08, 0x2f, 0xc0, 0x7d, 0xff, 0x94, 0x32,
	0xdd, 0x66, 0x25, 0x05, 0x27, 0x6c, 0x70, 0x1a, 0xf0, 0x92, 0x95, 0x2c, 0x6e, 0x54, 0x9e, 0xea,
	0x42, 0x4b, 0x0a, 0x4e, 0x5b, 0x71, 0xa3, 0xf2, 0xb7, 0xe6, 0x8e, 0x67, 0xe0, 0x48, 0x5a, 0x67,
	0xb2, 0x79, 0xdc, 0xe6, 0xc7, 0x47, 0x7c, 0x8f, 0x05, 0x5e, 0x02, 0xb4, 0x12, 0xb7, 0x0e, 0x39,
	0xe8, 0x32, 0xe1, 0xda, 0x39, 0x4c, 0x04, 0x55, 0x59, 0xad, 0x4b, 0xda, 0xea, 0x26, 0x3e, 0xe2,
	0xf8, 0xf8, 0x00, 0x63, 0x81, 0xd7, 0xe0, 0x1f, 0x99, 0xb8, 0xc8, 0xe1, 0xa2, 0xe9, 0x01, 0x37,
	0x6d, 0x61, 0x04, 0x9e, 0xd9, 0x49, 0x42, 0xbb, 0xfe, 0xd4, 0x56, 0x7f, 0xea, 0xf0, 0xe1, 0x38,
	0xb3, 0xc7, 0x1b, 0x70, 0x8c, 0xcc, 0x76, 0x2f, 0xf2, 0xdb, 0xc5, 0x2f, 0x3b, 0x57, 0x67, 0x88,
	0x9e, 0xc1, 0x37, 0xf4, 0x95, 0xea, 0xaf, 0x62, 0x45, 0x78, 0x0f, 0xde, 0x9a, 0x74, 0xf7, 0x67,
	0xf0, 0x7f, 0x98, 0x76, 0xe7, 0x7d, 0xb6, 0xcf, 0x87, 0x8c, 0xee, 0x7e, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x9d, 0x73, 0xb9, 0x60, 0xee, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmployeeServiceClient is the client API for EmployeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmployeeServiceClient interface {
	GetEmployee(ctx context.Context, in *EmployeeReq, opts ...grpc.CallOption) (*EmployeeRes, error)
}

type employeeServiceClient struct {
	cc *grpc.ClientConn
}

func NewEmployeeServiceClient(cc *grpc.ClientConn) EmployeeServiceClient {
	return &employeeServiceClient{cc}
}

func (c *employeeServiceClient) GetEmployee(ctx context.Context, in *EmployeeReq, opts ...grpc.CallOption) (*EmployeeRes, error) {
	out := new(EmployeeRes)
	err := c.cc.Invoke(ctx, "/proto.EmployeeService/getEmployee", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployeeServiceServer is the server API for EmployeeService service.
type EmployeeServiceServer interface {
	GetEmployee(context.Context, *EmployeeReq) (*EmployeeRes, error)
}

// UnimplementedEmployeeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEmployeeServiceServer struct {
}

func (*UnimplementedEmployeeServiceServer) GetEmployee(ctx context.Context, req *EmployeeReq) (*EmployeeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmployee not implemented")
}

func RegisterEmployeeServiceServer(s *grpc.Server, srv EmployeeServiceServer) {
	s.RegisterService(&_EmployeeService_serviceDesc, srv)
}

func _EmployeeService_GetEmployee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmployeeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeServiceServer).GetEmployee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.EmployeeService/GetEmployee",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeServiceServer).GetEmployee(ctx, req.(*EmployeeReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _EmployeeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EmployeeService",
	HandlerType: (*EmployeeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getEmployee",
			Handler:    _EmployeeService_GetEmployee_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/hr.proto",
}
